"""add lat lon to halls

Revision ID: 042a747ab3a7
Revises: 839c63c054fa
Create Date: 2026-05-03 11:52:37.449480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042a747ab3a7'
down_revision = '839c63c054fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('halls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('halls', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
