"""add city district venue_type and content_type

Revision ID: 839c63c054fa
Revises: fa70911d49c6
Create Date: 2026-05-01 12:17:01.806697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839c63c054fa'
down_revision = 'fa70911d49c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('halls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('venue_type', sa.String(length=20), nullable=False))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    with op.batch_alter_table('halls', schema=None) as batch_op:
        batch_op.drop_column('venue_type')
        batch_op.drop_column('district')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
